name: Build Neovim

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: imrehg/archlinux-makepkg:latest
    steps:
      - name: Initialize Container
        run: |
          sudo pacman -Syu --noconfirm
      - uses: actions/checkout@v2
      - name: Build
        run: |
          makepkg -s --noconfirm
          ls -l
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: neovim-nightly-x86_64
          path: ./neovim-nightly-git-*.pkg.tar.zst

  release:
    runs-on: ubuntu-latest
    container: imrehg/archlinux-makepkg:latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Initialize Container
        run: sudo pacman -Syu --noconfirm
      - name: Commit/Push git
        id: commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.name "archlinux-neovim CI"
          git config --local user.email "47162587+gamoutatsumi@users.noreply.github.com"
          git remote set-url origin https://gamoutatsumi:${GITHUB_TOKEN}@github.com/gamoutatsumi/archlinux-neovim-nightly.git
          git add PKGBUILD
          pkgver=$(grep pkgver= PKGBUILD | sed -e 's/pkgver=//')
          echo "::set-output name=version::$pkgver"
          git commit -m "${pkgver}-1"
          git push origin master
          git tag ${pkgver}-1
          git push origin ${pkgver}-1
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: neovim-nightly-x86_64
      - name: Create repo.db
        run: |
          repo-add archlinux-gamoutatsumi.db.tar.gz ./neovim-nightly-git-*.tar.*
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.commit.outputs.version }}-1
          name: ${{ steps.commit.outputs.version }}-1
          draft: false
          prerelease: false
          files: |
            ./neovim-nightly-git*.tar.*
            ./archlinux-gamoutatsumi.db
            ./archlinux-gamoutatsumi.files
